// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webapplication2.Models;

namespace Webapplication2.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Webapplication2.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Drama"
                        });
                });

            modelBuilder.Entity("Webapplication2.Models.MovieFormModel", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Alfred Hitchcock",
                            Edited = false,
                            LentTo = "Aidan",
                            Notes = "Good movie.",
                            Rating = "PG",
                            Title = "Vertigo",
                            Year = 1958
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 2,
                            Director = "Andrew Stanton",
                            Edited = false,
                            LentTo = "Aidan",
                            Notes = "Good movie.",
                            Rating = "G",
                            Title = "WALL-E",
                            Year = 2008
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 3,
                            Director = "Frank Darabont",
                            Edited = false,
                            LentTo = "Aidan",
                            Notes = "Good movie.",
                            Rating = "R",
                            Title = "Shawshank Redemption",
                            Year = 1994
                        });
                });

            modelBuilder.Entity("Webapplication2.Models.MovieFormModel", b =>
                {
                    b.HasOne("Webapplication2.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
